// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Urun_Denetim.Data;

#nullable disable

namespace Urun_Denetim.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20250220084212_AddKresFormTable")]
    partial class AddKresFormTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Urun_Denetim.Models.Admins", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("AdminAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminYetki")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Adminses");
                });

            modelBuilder.Entity("Urun_Denetim.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("KategoriAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarkaID")
                        .HasColumnType("int");

                    b.HasKey("KategoriID");

                    b.HasIndex("MarkaID");

                    b.ToTable("Kategoris");
                });

            modelBuilder.Entity("Urun_Denetim.Models.Marka", b =>
                {
                    b.Property<int>("MarkaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarkaID"));

                    b.Property<string>("MarkaAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkaID");

                    b.ToTable("Markas");
                });

            modelBuilder.Entity("Urun_Denetim.Models.Urunler", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunID"));

                    b.Property<int>("KategoriID")
                        .HasColumnType("int");

                    b.Property<int>("MarkaID")
                        .HasColumnType("int");

                    b.Property<string>("UrunAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UrunFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UrunStok")
                        .HasColumnType("int");

                    b.HasKey("UrunID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("MarkaID");

                    b.ToTable("Urunlers");
                });

            modelBuilder.Entity("Urun_Denetim.Models.Kategori", b =>
                {
                    b.HasOne("Urun_Denetim.Models.Marka", "Marka")
                        .WithMany("Kategoris")
                        .HasForeignKey("MarkaID");

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("Urun_Denetim.Models.Urunler", b =>
                {
                    b.HasOne("Urun_Denetim.Models.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Urun_Denetim.Models.Marka", "Marka")
                        .WithMany("Urunlers")
                        .HasForeignKey("MarkaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("Urun_Denetim.Models.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("Urun_Denetim.Models.Marka", b =>
                {
                    b.Navigation("Kategoris");

                    b.Navigation("Urunlers");
                });
#pragma warning restore 612, 618
        }
    }
}
